#
# Copyright (c) 2020-2023, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: 2.1

commands:
  install_sdk:
    description: "Install the Daml SDK"
    parameters:
      version:
        type: string
    steps:
      - run:
          command: |
            cd ${HOME}
            wget https://github.com/digital-asset/daml/releases/download/v<< parameters.version >>/daml-sdk-<< parameters.version >>-linux.tar.gz
            tar -zxvf daml-sdk-<< parameters.version >>-linux.tar.gz
            cd sdk-<< parameters.version >>
            ./install.sh
            cd ${HOME}
            rm -rf sdk-<< parameters.version >>


jobs:
  build:
    docker:
     - image: cimg/python:3.11-browsers

    steps:
      - checkout
      - restore_cache:
          keys:
            - daml-{{ checksum "daml.yaml" }}
      - install_sdk:
          version: "2.7.6"
      - save_cache:
          paths:
            - ~/.daml
          key: daml-{{ checksum "daml.yaml" }}
      - run:
          command: |
            export PATH=${HOME}/.daml/bin:${PATH}
            make build
